# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=32)),
                ('worldview', models.CharField(max_length=32)),
                ('quote', models.CharField(max_length=128)),
            ],
        ),
    ]
