# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0004_auto_20170314_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.OneToOneField(max_length=32, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='persona',
            name='occupation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='persona',
            name='quote',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='persona',
            name='surname',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='persona',
            name='worldview',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
