# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0005_auto_20170323_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='host',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='chain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(max_length=32),
        ),
    ]
